### ISSUE TITLE
[epic] Workflow to turn text in GDoc into a Brevo email course

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/brevo-utils#1]
When i have text drafted in google docs or markdown I want to "click a button" to turn it into a single email OR a course (automation) in Brevo so that i avoid time consuming and error prone copying and pasting and can work in one place but use another tool for email (i.e. i can have best of both worlds: drafting and editing in gdocs or markdown *and* using brevo for email stuff)

Extending pilot done in life-itself/diginomics#86. 

## Design

https://link.excalidraw.com/l/9u8crB2ZmUo/3aW9SZ0aW3C

![image](https://github.com/life-itself/diginomics/assets/180658/bab5bf4e-05b8-4363-8db0-024449957919)

## Acceptance

Markdown to Brevo

- [ ] Can take source markdown files and create brevo templates
- [x] #2
- [ ] Is repeatable (i.e. upsert supported)?
- [ ] Documented steps for non-tech people

Gdocs to Markdown

FUTURE
