### ISSUE TITLE
Can add optional header and footer to each email template

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/brevo-utils#2]
When creating an email template i want to add a standard header and footer (especially useful for courses).

## Acceptance

- [x] Can specify in `config.js` or similar a header markdown file (or html?) **✅2023-05-30 commit https://github.com/life-itself/brevo-utils/commit/534e7e1ab4980e204a7ec153d291c1064dd78cf3**
- [x]  and a footer markdown file (or html) **✅ 2023-05-30**
- [ ] 🏆 Can have "skip ahead" functionality i.e. get next episode straight away (FUTURE)

## Tasks

- [x] create `config.js` with header and footer path options eg. 
    `export default { header: "...path to header file" }`
- [x] header / footer markdown with html support

**Comment by rufuspollock** [comment]
FIXED. All done!
